name: Build

on:
  push:
    branches: ['main', 'dev']
    tags: v*
  pull_request:
    branches: ['main', 'dev']
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        variant:
          - { os: windows-latest, arch: x64, crt: MT }
          - { os: windows-latest, arch: x64, crt: MD }
          #- { os: windows-11-arm, arch: arm64, crt: MT } disabled due to bochscpu-build not supporting this
          #- { os: windows-11-arm, arch: arm64, crt: MD }
          - { os: ubuntu-latest, arch: x64  }
          - { os: ubuntu-24.04-arm, arch: arm64 }
          - { os: macos-latest, arch: arm64  }
    runs-on: ${{ matrix.variant.os }}
    name: ${{ matrix.variant.os }} / ${{ matrix.variant.arch }} ${{ matrix.variant.crt }}
    env:
      RUSTUP_TOOLCHAIN: stable
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          path: bochscpu-ffi

      - name: Determine dependency branch
        run: |
          if [ "${{ github.event_name }}" = "pull_requset" ]; then
            if [ "${{ github.base_ref }}" = "dev" ]; then
              echo "DEP_BRANCH=dev" >> $GITHUB_ENV
            else
              echo "DEP_BRANCH=main" >> $GITHUB_ENV
            fi
          else
            if [ "${{ github.ref_name }}" = "dev" ]; then
              echo "DEP_BRANCH=dev" >> $GITHUB_ENV
            else
              echo "DEP_BRANCH=main" >> $GITHUB_ENV
            fi
          fi
        shell: bash

      - name: Checkout bochscpu dependency
        uses: actions/checkout@v7
        with:
          repository: 'yrp604/bochscpu'
          path: bochscpu
          ref: ${{ env.DEP_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: env.DEP_BRANCH == 'dev' && !startsWith(matrix.variant.os, 'windows-')
        run: |
          gh api repos/yrp604/bochscpu-build/actions/artifacts \
            --jq '.artifacts[] | select(.name=="bochscpu-build-${{ matrix.variant.os }}-${{ matrix.variant.arch }}") | .id' \
          | head -1 \
          | xargs -I {} gh api repos/yrp604/bochscpu-build/actions/artifacts/{}/zip > artifact.zip
          unzip artifact.zip -d bochscpu
          ls
        env:
          GH_TOKEN: ${{ secrets.BOCHSCPU_BUILD }}

      - if: env.DEP_BRANCH == 'dev' && startsWith(matrix.variant.os, 'windows-')
        run: |
          $artifactId = gh api repos/yrp604/bochscpu-build/actions/artifacts `
            --jq '.artifacts[] | select(.name=="bochscpu-build-${{ matrix.variant.os }}-${{ matrix.variant.arch }}-${{ matrix.variant.crt }}") | .id ' | Select-Object -First 1
          gh api repos/yrp604/bochscpu-build/actions/artifacts/$artifactId/zip > artifact.zip
          Expand-Archive -Path artifact.zip -DestinationPath bochscpu
        env:
          GH_TOKEN: ${{ secrets.BOCHSCPU_BUILD }}

      - if: ${{ !startsWith(matrix.variant.os, 'macos') }}
        run: |
          # skip `rustup self update` on macos as rustup seems to be installed through brew
          rustup self update

      - run: |
          rustup upgrade
          rustup show

      - if: startsWith(matrix.variant.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config libssl-dev cmake g++

      - name: Configure CRT flags (Windows)
        if: ${{ startsWith(matrix.variant.os, 'windows-') }}
        run: |
          if [ "${{ matrix.variant.crt }}" = "MT" ]; then
            echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
          else
            echo "RUSTFLAGS=-C target-feature=-crt-static" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Build (release)
        run: cargo build --release
        working-directory: bochscpu-ffi

      - name: Upload artifacts (Linux/Mac)
        if: ${{ !startsWith(matrix.variant.os, 'windows-') }}
        uses: actions/upload-artifact@v7
        with:
          name: bochscpu-ffi-${{ matrix.variant.os }}-${{ matrix.variant.arch }}
          path: bochscpu-ffi/target/*/libbochscpu*

      - name: Upload artifacts (Windows)
        if: ${{ startsWith(matrix.variant.os, 'windows-') }}
        uses: actions/upload-artifact@v7
        with:
          name: bochscpu-ffi-${{ matrix.variant.os }}-${{ matrix.variant.arch }}-${{ matrix.variant.crt}}
          path: bochscpu-ffi/target/*/bochscpu*
